### Post a message to RabbitMQ queue
POST http://localhost:15672/api/exchanges/%2F/amq.default/publish
Authorization: Basic bXl1c2VyOm15cGFzc3dvcmQ=
Content-Type: application/json

{
  "properties": {},
  "routing_key": "payload_delivery_queue",
  "payload": "{\"sellerId\": \"e53a47fa-9f1b-4d58-8981-cdd01beac39e\", \"tons\": 300, \"arrivalTime\": \"2024-10-15T15:04:00\", \"materialType\": \"GYPSUM\"}",
  "payload_encoding": "string"
}


### Post a message to RabbitMQ queue
POST http://localhost:15672/api/exchanges/%2F/amq.default/publish
Authorization: Basic bXl1c2VyOm15cGFzc3dvcmQ=
Content-Type: application/json

{
  "properties": {},
  "routing_key": "commissions_queue",
  "payload": "{\"orderLines\": [{\"materialType\": \"GYPSUM\", \"quantity\": 1.0, \"uom\": \"kt\"}], \"sellerId\": \"e53a47fa-9f1b-4d58-8981-cdd01beac39e\", \"poNumber\": \"PO-12345\"}",
  "payload_encoding": "string"
}
