### POST Test create appointment
POST http://localhost:8091/lsc/appointment/e53a47fa-9f1b-4d58-8981-cdd01beac39e
Content-Type: application/json

{
  "licensePlate": "B-123JD-F",
  "materialType": "GYPSUM",
  "scheduleDateTime": "2024-10-13T15:00:00"
}


### POST Test license plate on gate recognition
POST http://localhost:8091/lsc/gate/B-123JD-F/arrive
Content-Type: application/json

{}

### POST Test pass weighing bridge (enter operation)
POST http://localhost:8091/lsc/bridge/B-123JD-F/500/true
Content-Type: application/json

{}

### POST Test truck docking to conveyour belt to drop payload
POST http://localhost:8091/lsc/conveyorBelt/B-123JD-F
Content-Type: application/json

{}

### POST Test truck pass weighing bridge (leave operation)
POST http://localhost:8091/lsc/bridge/B-123JD-F/300/false
Content-Type: application/json

{}