### POST input vessel and shipment order info
POST http://localhost:8094/wsc/arrivals/V12345
Content-Type: application/json

{
  "purchaseOrderNumber": "PO123456",
  "customerEnterpriseNumber": "ENT789012",
  "departureDate": "2024-11-06"
}

### POST input vessel and shipment order info
POST http://localhost:8094/wsc/arrivals/V1654
Content-Type: application/json

{
  "purchaseOrderNumber": "PO7891",
  "customerEnterpriseNumber": "ENT789012",
  "departureDate": "2024-11-16"
}


### POST match SO and PO
POST http://localhost:8094/wsc/vessels/V1654/matchOrders

### POST plan bunkering operation
POST http://localhost:8094/wsc/vessels/V1654/bunkeringOperations/2024-11-04


### POST complete vesel inspection
POST http://localhost:8094/wsc/vessels/V1654/inspectionOperations/Mykhailo-Kruts

### POST check if vessel can leave
POST http://localhost:8094/wsc/vessels/V12345

### Get all ships with outstanding IO's
GET http://localhost:8094/wsc/vessels/outstanding-inspection-operations

### Get all shipments arrivals
GET http://localhost:8094/wsc/arrivals