server:
  port: ${PORT:8094}
  servlet:
    context-path: /wsc


spring:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: "jdbc:mysql://localhost:13306/waterside"
    username: app_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8180/realms/kdg_realm/protocol/openid-connect/certs
            issuer-uri: http://localhost:8180/realms/kdg_realm